upstream php {
    server php:9000;
}

server {
    listen 80;
    server_name localhost;

    root /app/public;
    index index.php;

    client_max_body_size 20M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        
        # Éviter les erreurs "Primary script unknown"
        if (!-f $realpath_root$fastcgi_script_name) {
            return 404;
        }
    }

    location ~ /\. {
        deny all;
    }

    location ~ /\.git {
        deny all;
    }

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}
